// Generated by gencpp from file accumulator/SendUIntRequest.msg
// DO NOT EDIT!


#ifndef ACCUMULATOR_MESSAGE_SENDUINTREQUEST_H
#define ACCUMULATOR_MESSAGE_SENDUINTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/UInt16.h>

namespace accumulator
{
template <class ContainerAllocator>
struct SendUIntRequest_
{
  typedef SendUIntRequest_<ContainerAllocator> Type;

  SendUIntRequest_()
    : data()  {
    }
  SendUIntRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::UInt16_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::accumulator::SendUIntRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::accumulator::SendUIntRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SendUIntRequest_

typedef ::accumulator::SendUIntRequest_<std::allocator<void> > SendUIntRequest;

typedef boost::shared_ptr< ::accumulator::SendUIntRequest > SendUIntRequestPtr;
typedef boost::shared_ptr< ::accumulator::SendUIntRequest const> SendUIntRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::accumulator::SendUIntRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::accumulator::SendUIntRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::accumulator::SendUIntRequest_<ContainerAllocator1> & lhs, const ::accumulator::SendUIntRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::accumulator::SendUIntRequest_<ContainerAllocator1> & lhs, const ::accumulator::SendUIntRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace accumulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::accumulator::SendUIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::accumulator::SendUIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::accumulator::SendUIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::accumulator::SendUIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accumulator::SendUIntRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accumulator::SendUIntRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::accumulator::SendUIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f455a629b65bfa4a5fc34338259477ad";
  }

  static const char* value(const ::accumulator::SendUIntRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf455a629b65bfa4aULL;
  static const uint64_t static_value2 = 0x5fc34338259477adULL;
};

template<class ContainerAllocator>
struct DataType< ::accumulator::SendUIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "accumulator/SendUIntRequest";
  }

  static const char* value(const ::accumulator::SendUIntRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::accumulator::SendUIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/UInt16 data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt16\n"
"uint16 data\n"
;
  }

  static const char* value(const ::accumulator::SendUIntRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::accumulator::SendUIntRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendUIntRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::accumulator::SendUIntRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::accumulator::SendUIntRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    s << std::endl;
    Printer< ::std_msgs::UInt16_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACCUMULATOR_MESSAGE_SENDUINTREQUEST_H
