// Generated by gencpp from file accumulator/SendUIntResponse.msg
// DO NOT EDIT!


#ifndef ACCUMULATOR_MESSAGE_SENDUINTRESPONSE_H
#define ACCUMULATOR_MESSAGE_SENDUINTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace accumulator
{
template <class ContainerAllocator>
struct SendUIntResponse_
{
  typedef SendUIntResponse_<ContainerAllocator> Type;

  SendUIntResponse_()
    {
    }
  SendUIntResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::accumulator::SendUIntResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::accumulator::SendUIntResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SendUIntResponse_

typedef ::accumulator::SendUIntResponse_<std::allocator<void> > SendUIntResponse;

typedef boost::shared_ptr< ::accumulator::SendUIntResponse > SendUIntResponsePtr;
typedef boost::shared_ptr< ::accumulator::SendUIntResponse const> SendUIntResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::accumulator::SendUIntResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::accumulator::SendUIntResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace accumulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::accumulator::SendUIntResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::accumulator::SendUIntResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::accumulator::SendUIntResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::accumulator::SendUIntResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accumulator::SendUIntResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accumulator::SendUIntResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::accumulator::SendUIntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::accumulator::SendUIntResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::accumulator::SendUIntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "accumulator/SendUIntResponse";
  }

  static const char* value(const ::accumulator::SendUIntResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::accumulator::SendUIntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::accumulator::SendUIntResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::accumulator::SendUIntResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendUIntResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::accumulator::SendUIntResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::accumulator::SendUIntResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ACCUMULATOR_MESSAGE_SENDUINTRESPONSE_H
