// Generated by gencpp from file accumulator/SendPatterns.msg
// DO NOT EDIT!


#ifndef ACCUMULATOR_MESSAGE_SENDPATTERNS_H
#define ACCUMULATOR_MESSAGE_SENDPATTERNS_H

#include <ros/service_traits.h>


#include <accumulator/SendPatternsRequest.h>
#include <accumulator/SendPatternsResponse.h>


namespace accumulator
{

struct SendPatterns
{

typedef SendPatternsRequest Request;
typedef SendPatternsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendPatterns
} // namespace accumulator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::accumulator::SendPatterns > {
  static const char* value()
  {
    return "2c56ad93b5e5b74eee9a0de2a6311764";
  }

  static const char* value(const ::accumulator::SendPatterns&) { return value(); }
};

template<>
struct DataType< ::accumulator::SendPatterns > {
  static const char* value()
  {
    return "accumulator/SendPatterns";
  }

  static const char* value(const ::accumulator::SendPatterns&) { return value(); }
};


// service_traits::MD5Sum< ::accumulator::SendPatternsRequest> should match
// service_traits::MD5Sum< ::accumulator::SendPatterns >
template<>
struct MD5Sum< ::accumulator::SendPatternsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::accumulator::SendPatterns >::value();
  }
  static const char* value(const ::accumulator::SendPatternsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::accumulator::SendPatternsRequest> should match
// service_traits::DataType< ::accumulator::SendPatterns >
template<>
struct DataType< ::accumulator::SendPatternsRequest>
{
  static const char* value()
  {
    return DataType< ::accumulator::SendPatterns >::value();
  }
  static const char* value(const ::accumulator::SendPatternsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::accumulator::SendPatternsResponse> should match
// service_traits::MD5Sum< ::accumulator::SendPatterns >
template<>
struct MD5Sum< ::accumulator::SendPatternsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::accumulator::SendPatterns >::value();
  }
  static const char* value(const ::accumulator::SendPatternsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::accumulator::SendPatternsResponse> should match
// service_traits::DataType< ::accumulator::SendPatterns >
template<>
struct DataType< ::accumulator::SendPatternsResponse>
{
  static const char* value()
  {
    return DataType< ::accumulator::SendPatterns >::value();
  }
  static const char* value(const ::accumulator::SendPatternsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACCUMULATOR_MESSAGE_SENDPATTERNS_H
