// Generated by gencpp from file accumulator/SendUInt.msg
// DO NOT EDIT!


#ifndef ACCUMULATOR_MESSAGE_SENDUINT_H
#define ACCUMULATOR_MESSAGE_SENDUINT_H

#include <ros/service_traits.h>


#include <accumulator/SendUIntRequest.h>
#include <accumulator/SendUIntResponse.h>


namespace accumulator
{

struct SendUInt
{

typedef SendUIntRequest Request;
typedef SendUIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendUInt
} // namespace accumulator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::accumulator::SendUInt > {
  static const char* value()
  {
    return "f455a629b65bfa4a5fc34338259477ad";
  }

  static const char* value(const ::accumulator::SendUInt&) { return value(); }
};

template<>
struct DataType< ::accumulator::SendUInt > {
  static const char* value()
  {
    return "accumulator/SendUInt";
  }

  static const char* value(const ::accumulator::SendUInt&) { return value(); }
};


// service_traits::MD5Sum< ::accumulator::SendUIntRequest> should match
// service_traits::MD5Sum< ::accumulator::SendUInt >
template<>
struct MD5Sum< ::accumulator::SendUIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::accumulator::SendUInt >::value();
  }
  static const char* value(const ::accumulator::SendUIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::accumulator::SendUIntRequest> should match
// service_traits::DataType< ::accumulator::SendUInt >
template<>
struct DataType< ::accumulator::SendUIntRequest>
{
  static const char* value()
  {
    return DataType< ::accumulator::SendUInt >::value();
  }
  static const char* value(const ::accumulator::SendUIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::accumulator::SendUIntResponse> should match
// service_traits::MD5Sum< ::accumulator::SendUInt >
template<>
struct MD5Sum< ::accumulator::SendUIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::accumulator::SendUInt >::value();
  }
  static const char* value(const ::accumulator::SendUIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::accumulator::SendUIntResponse> should match
// service_traits::DataType< ::accumulator::SendUInt >
template<>
struct DataType< ::accumulator::SendUIntResponse>
{
  static const char* value()
  {
    return DataType< ::accumulator::SendUInt >::value();
  }
  static const char* value(const ::accumulator::SendUIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACCUMULATOR_MESSAGE_SENDUINT_H
