// Generated by gencpp from file accumulator/SendStringRequest.msg
// DO NOT EDIT!


#ifndef ACCUMULATOR_MESSAGE_SENDSTRINGREQUEST_H
#define ACCUMULATOR_MESSAGE_SENDSTRINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace accumulator
{
template <class ContainerAllocator>
struct SendStringRequest_
{
  typedef SendStringRequest_<ContainerAllocator> Type;

  SendStringRequest_()
    : data()  {
    }
  SendStringRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::accumulator::SendStringRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::accumulator::SendStringRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SendStringRequest_

typedef ::accumulator::SendStringRequest_<std::allocator<void> > SendStringRequest;

typedef boost::shared_ptr< ::accumulator::SendStringRequest > SendStringRequestPtr;
typedef boost::shared_ptr< ::accumulator::SendStringRequest const> SendStringRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::accumulator::SendStringRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::accumulator::SendStringRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::accumulator::SendStringRequest_<ContainerAllocator1> & lhs, const ::accumulator::SendStringRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::accumulator::SendStringRequest_<ContainerAllocator1> & lhs, const ::accumulator::SendStringRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace accumulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::accumulator::SendStringRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::accumulator::SendStringRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::accumulator::SendStringRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::accumulator::SendStringRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accumulator::SendStringRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accumulator::SendStringRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::accumulator::SendStringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "131c7b16e90d7646b67a1c83cd590279";
  }

  static const char* value(const ::accumulator::SendStringRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x131c7b16e90d7646ULL;
  static const uint64_t static_value2 = 0xb67a1c83cd590279ULL;
};

template<class ContainerAllocator>
struct DataType< ::accumulator::SendStringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "accumulator/SendStringRequest";
  }

  static const char* value(const ::accumulator::SendStringRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::accumulator::SendStringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::accumulator::SendStringRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::accumulator::SendStringRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendStringRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::accumulator::SendStringRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::accumulator::SendStringRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACCUMULATOR_MESSAGE_SENDSTRINGREQUEST_H
